#include "EngineCore/stdafx.h"

RTTR_REGISTRATION
{
    using namespace rttr;

	RTTR_REGISTRATION_STANDARD_TYPE_VARIANTS( DirectX::XMFLOAT2 )
	RTTR_REGISTRATION_STANDARD_TYPE_VARIANTS( DirectX::XMFLOAT3 )
	RTTR_REGISTRATION_STANDARD_TYPE_VARIANTS( DirectX::XMFLOAT4 )
}